Repository opensource-sw-5/Vata-BE, pull requests merged in 2025-06, with the labels that each got.

#30 feat(#15): 프로필 보관함 리스트 불러오기
  src/main/java/com/vata/common/web/PagingResult.java
  src/main/java/com/vata/profile/application/ProfileFacade.java
  src/main/java/com/vata/profile/controller/ProfileController.java
  src/main/java/com/vata/profile/controller/dto/ProfileListResponse.java
  src/main/java/com/vata/profile/controller/swagger/ProfileControllerSpec.java
  src/main/java/com/vata/profile/domain/repository/ProfileRepository.java
  src/main/java/com/vata/profile/domain/service/ProfileService.java
Labels: 🧩 backend, 🔥 feat

#35 infra(#33): nginx 설정 및 https 적용
  src/main/java/com/vata/HealthCheckController.java
  src/main/java/com/vata/common/configuration/WebConfig.java
Labels: 🏘️ infra, 🧩 backend

#34 feat(#16): Stability AI access token 개수 불러오기 api
  src/main/java/com/vata/profile/controller/ProfileController.java
  src/main/java/com/vata/profile/controller/dto/StabilityCreditsResponse.java
  src/main/java/com/vata/profile/controller/swagger/ProfileControllerSpec.java
  src/main/java/com/vata/profile/domain/service/StabilityBalanceService.java
  src/main/java/com/vata/profile/infrastructure/StabilityRestClient.java
  src/main/resources/application.yml
Labels: 🧩 backend, 🔥 feat

#36 feat(#32): open api 호출 동기 -> 비동기 방식으로 변경
  gradle/spring.gradle
  src/main/java/com/vata/auth/application/AuthFacade.java
  src/main/java/com/vata/common/configuration/WebClientConfig.java
  src/main/java/com/vata/profile/application/ProfileFacade.java
  src/main/java/com/vata/profile/application/ProfilePromptFacade.java
  src/main/java/com/vata/profile/controller/ProfileController.java
  src/main/java/com/vata/profile/controller/swagger/ProfileControllerSpec.java
  src/main/java/com/vata/profile/domain/service/StabilityImageService.java
  src/main/java/com/vata/profile/infrastructure/StabilityRestClient.java
  src/main/java/com/vata/profile/infrastructure/StabilityRestTemplate.java
  src/main/java/com/vata/profile/infrastructure/StabilityWebClient.java
  src/main/resources/application.yml
Labels: 🧩 backend, 🪜 refactor

#37 docs: Update README.md
  README.md
Labels: 📝 docs, 🧹 chore
